steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMAGE_NAME}'
    - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - '${_IMAGE_NAME}'

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: 
  - 'run'
  - 'deploy'
  - 'gcp-ingest-api'
  - '--image'
  - '${_IMAGE_NAME}'
  - '--region'
  - 'us-central1'
  - '--update-env-vars'
  - 'PROJECT_ID=$PROJECT_ID,TOPIC_ID=${_TOPIC_ID}'

substitutions:
    _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/gcp-ingest-api:${BUILD_ID}'

options:
    dynamic_substitutions: true
    substitution_option: 'ALLOW_LOOSE'

images:
- ${_IMAGE_NAME}


