steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - '${_IMAGE_NAME}'
    - '.'

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'push'
  - '${_IMAGE_NAME}'

substitutions:
    _IMAGE_NAME: us-central1-docker.pkg.dev/${PROJECT_ID}/docker-repo/gcp-ingest-api:${BUILD_ID}

options:
    dynamic_substitutions: true

images:
- ${_IMAGE_NAME}
